[package]
name = "midi-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
rand = "0.8"
walkdir = "2"
indicatif = "0.17"
encoding_rs = "0.8"
